services:
  - type: web
    name: bareprop-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    rootDir: backend
    envVars:
      - key: PORT
        value: 5000
      - key: NODE_ENV
        value: production
      - key: DB_DATABASE
        value: barepropdb
      - key: DB_PORT
        value: 5432
      - key: TEST_MODE
        value: false
      - key: DB_HOST
        fromDatabase:
          name: bareprop-db
          property: host
      - key: DB_PASSWORD
        fromDatabase:
          name: bareprop-db
          property: password
      - key: DB_USER
        fromDatabase:
          name: bareprop-db
          property: user
      - key: JWT_SECRET
        generateValue: true
      - key: FRONTEND_URL
        value: https://bareprop-frontend.onrender.com
      - key: RSTOCK_BASE_URL
        value: https://api.stockstrader.com/api/v1
      - key: STOCKSTRADER_TOKEN
        sync: false
      - key: STOCKSTRADER_ACCOUNT_ID
        sync: false

  - type: web
    name: bareprop-frontend
    env: static
    plan: free
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: VITE_API_URL
        fromService:
          type: web
          name: bareprop-backend
          property: url

databases:
  - name: bareprop-db
    plan: free
    databaseName: barepropdb
    user: barepropdbuser